### PR TITLE
Refactor Sources and Workflow

### LINKED ISSUE #129: Sources.kt:84: if output directory already exists...
The puzzle `119-1e2fda85` from #119 has to be resolved: 

https://github.com/objectionary/ddr/blob/32b5c8c744ffe6cd78d6143b7f862dce9cc6d5b6/src/main/kotlin/org/objectionary/ddr/sources/Sources.kt#L84-L84

The puzzle was created by @c71n93 on 20-Jul-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by c71n93**
Closes #129 and #130. Also fixed DdrWorkflow constructor. Now the secondary constructor is delegated to the superclass.

---

## PR-Codex overview
This PR focuses on updating the codebase to use `java.nio.file.Path` instead of `String` for file paths. 

### Detailed summary
- Updated file paths from `String` to `Path` in various classes
- Modified constructor and method signatures to accept `Path` instead of `String`

> The following files were skipped due to too many changes: `src/main/kotlin/org/objectionary/ddr/launch/DdrWorkflow.kt`, `src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt`, `src/main/kotlin/org/objectionary/ddr/sources/Sources.kt`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by c71n93** [comment]
@Graur could you review this one, please?

**Review by Graur — CHANGES_REQUESTED** [review]
@c71n93 Nice refactoring
@yegor256 Please take a look

**Comment by c71n93** [comment]
@yegor256 could you take a look, please?

**Comment by c71n93** [comment]
@yegor256 could you take a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
