### PR TITLE
Fix Workflow class hierarchy

### LINKED ISSUE #117: Implement Workflow interface
For more general use of the [`DdrWorkflow`](https://github.com/objectionary/ddr/blob/d9d6fcf1b195ef09b8e29add530c0ff35639f693/src/main/kotlin/org/objectionary/ddr/launch/DdrWorkflow.kt#L19) class in other projects (https://github.com/objectionary/aoi/issues/63), it must be reimplemented.

Other projects use similar logic, so we need to associate the DdrWorkflow class with others. Otherwise, it turns out a copy paste ([`AoiWorkflow`](https://github.com/objectionary/aoi/blob/c0306e96143775de6f5966501baab3a62b30147f/src/main/kotlin/org/objectionary/aoi/launch/AoiWorkflow.kt#L48) class)

### PR DESCRIPTION
**Pull request by c71n93**
closes #117

---

### Focus of this PR:
This PR focuses on renaming and restructuring classes and interfaces related to the workflow in the codebase.

### Detailed summary:
- Renamed `IntegrationDdrLaunchedBase` to `IntegrationDdrWorkflowBase`.
- Renamed `DdrWorkflow` to `XmirAnalysisWorkflow`.
- Added a new interface `Workflow` with a `launch()` function.
- Updated `DdrWorkflow` to extend `XmirAnalysisWorkflow` and implement `Workflow`.
- Updated the `launch()` function in `DdrWorkflow` to override the one in `XmirAnalysisWorkflow`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by c71n93** [comment]
@mximp Could you review this, please?

**Comment by c71n93** [comment]
@Graur Could you review, please?

**Review by Graur — APPROVED** [review]
@c71n93 It's very unusual to see the interface and the abstract class and a plane class in one `.kt` file. But I know it is ok for Kotlin for some reason. The rest is look good to me.
@yegor256 Could you please have a look?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
